### PR TITLE
Using dig for error handling

### PR DESCRIPTION
**Pull request by vkghub**
[ME-180442272](https://www.pivotaltracker.com/n/projects/2502930/stories/180442272)

### CODE REVIEW

**Review by markgoho — CHANGES_REQUESTED** [review]
are there any specs we could add that would demonstrate the difference between having dig and not having dig?

**Comment by ZASMan** [comment]
> are there any specs we could add that would demonstrate the difference between having dig and not having dig?

not exactly, it'll prevent an exception from being thrown and it will hit the success/failure appropriately in Monads as suspected and not hold people up

**Comment by markgoho** [comment]
@ZASMan @vkghub  is it possible to write a cucumber that fails without this fix and then passes with it?

**Review by bill-transue — CHANGES_REQUESTED** [review]
When we have incomplete results we need to fail the CV3 application transform. Take a look at f3135bc31030bc6f6b1b224e28c34f09e48e10f8 where I'm failing the transform.

**Comment by bill-transue** [comment]
This actually isn't really needed anymore since the `FetchLcsp` and `FetchSlcsp` operations now fail when they have incomplete results. Which is what was causing the nil return off that first key in the first place. Now when either of those operations fail and this method will return (on lines 659 and 662) that fail before these lines are reached. That being said, using a dig here wouldn't hurt.

**Comment by bill-transue** [comment]
At this point we've dealt with a potential (S)Lcsp fetch problem 3 other ways, and we should no longer have incomplete results, and if we do it will be caught. Thanks @vkghub for initially writing this, but we definitely want this operation to fail if plans can't be matched to members.

**Pull request closed without merging**
