### PR TITLE
Match ME towns to counties for fix counties rake task

### PR DESCRIPTION
**Pull request by ZASMan**
ME-180546321

### CODE REVIEW

**Review by bill-transue — DISMISSED** [review]
Adds towns to match up counties. This is a great improvement to the county fixer to help get more counties filled in. Nice work @ZASMan!

**Review by markgoho — DISMISSED** [review]
@ZASMan the title of the PR is "add data for maine counties" but I see much more in the PR than just added data

this should probably be split this into two Pull Requests

**Comment by ZASMan** [comment]
> @ZASMan the title of the PR is "add data for maine counties" but I see much more in the PR than just added data
> 
> this should probably be split this into two Pull Requests

No, it probably shouldn't. Perhaps the title was off, a better description is "add maine town/counties matching hash to match nil counties"

**Review by bill-transue — APPROVED** [review]
Adds towns to match up counties. This is a great improvement to the county fixer to help get more counties filled in. Nice work @ZASMan!

**Pull request merged**
