### PR TITLE
enrollment tile design & ui cleanup

### PR DESCRIPTION
**Pull request by scaustin34**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: TT6-185453339

# A brief description of the changes

Current behavior:

New behavior: strictly style changes

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:
ENROLLMENT_PLAN_TILE_UPDATE_IS_ENABLED

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

### CODE REVIEW

**Review by yosefserkez — APPROVED** [review]
CSS ninja! Nice work

**Review by erubinst — APPROVED** [review]
Looks great - nice use of css vars for the button colors so no hardcoded colors

**Comment by yosefserkez** [comment]
I believe the feature flag variable for this is actually VERBOSE_SEP_MESSAGE_IS_ENABLED. @scaustin34 can you confirm?

**Comment by scaustin34** [comment]
> I believe the feature flag variable for this is actually VERBOSE_SEP_MESSAGE_IS_ENABLED. @scaustin34 can you confirm?

for the sep message, yes. The bulk of the changes are just under the refactoring.

**Pull request merged**
