### PR TITLE
Check for ssn already in use 

### PR DESCRIPTION
**Pull request by quisbertdiana**
Added scenario for SSN already in use

### CODE REVIEW

**Review by raghuramg — DISMISSED** [review]
Added feature to validate SSN already in use. Feature looks good. Please promote for testing

**Comment by jacobkagon** [comment]
Will work with Diana to fix this merge conflict

**Review by raghuramg — APPROVED** [review]
branch rebased

**Review by raghuramg — APPROVED** [review]
branch rebased...please promote for testing

**Review by jacobkagon — APPROVED** [review]
No ticket necessary for this. Thanks @quisbertdiana

**Pull request merged**
