### PR TITLE
Extend IVL OE end date

### PR DESCRIPTION
**Pull request by utkarsh7989**
RM-97597

### CODE REVIEW

**Review by markgoho — DISMISSED** [review]
@utkarsh7989 why are we making this change in the base `settings.yml` file instead of the dc-specific file?

**Comment by utkarsh7989** [comment]
@markgoho this feature has not been implemented yet to use resource registry.

**Review by vineelvineel — APPROVED** [review]
LGTM

**Review by angus-irvine — APPROVED** [review]
Config looks good (common change we make every year).

**Pull request merged**
