### PR TITLE
Add broker info to cv3 family

### PR DESCRIPTION
**Pull request by nisanthyaganti9**
ME-180403015

### CODE REVIEW

**Review by markgoho — DISMISSED** [review]
are there tests that can be written for this change?

**Comment by nisanthyaganti9** [comment]
> are there tests that can be written for this change?

currently there's no spec for this operation. And, adding a spec to this file is much bigger effort than what we're doing in this story. It can be a seperate task i believe.

**Comment by markgoho** [comment]
> It can be a seperate task i believe.

No, please add the spec in this PR

**Comment by markgoho** [comment]
@nisanthyaganti9 I spoke with @kristinmerbach and we've decided to move forward with this PR without the spec....it still needs a review of the code, but for now we'll add a ticket to our backlog to add the spec

**Comment by nisanthyaganti9** [comment]
> @nisanthyaganti9 I spoke with @kristinmerbach and we've decided to move forward with this PR without the spec....it still needs a review of the code, but for now we'll add a ticket to our backlog to add the spec

just curious, why?

**Review by kristinmerbach — COMMENTED** [review]
Need to resolve the rubocop issues, just looks like some comma things. Other than that looks good.

**Comment by nisanthyaganti9** [comment]
> Need to resolve the rubocop issues, just looks like some comma things. Other than that looks good.

I hate to do  this rubocop change. I'm so inclined towards adding comma;s at the end to the hash.

**Review by kristinmerbach — APPROVED** [review]

**Pull request merged**
