### PR TITLE
add consumer bookmark url link

### PR DESCRIPTION
**Pull request by harshared**
ME-180412223

### CODE REVIEW

**Review by bill-transue — APPROVED** [review]
Adds a link to the person's consumer role bookmark url, which should be the identity verification page if they're at this step. Good work @harshared!

**Comment by bill-transue** [comment]
I know this well be read because of the failures in `trunk`.

**Review by markgoho — CHANGES_REQUESTED** [review]
@harshared @bill-transue is there a cucumber we could add here to ensure this behavior isn't accidentally changed in the future without a test failing?

**Review by markgoho — APPROVED** [review]
moving forward without tests

**Comment by markgoho** [comment]
closing in favor of (#1385)

**Pull request closed without merging**
