### PR TITLE
changes hbx id generation logic to return an integer in development env

### PR DESCRIPTION
**Pull request by yosefserkez**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: TT6-185618609

# A brief description of the changes

Current behavior:

Outside of Production hbx_id's are generated as strings, where aca_entities expects Integers.

New behavior:
Id's are integers

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

The generator combines the uniqueness of the current time with a random number to avoid collisions.

### CODE REVIEW

**Comment by mdkaraman** [comment]
I've found an issue with the Mitc transformers that requires us to limit the length of the generated Id's to 15 or fewer digits.  

The id is getting converted to a float by the transforms (not totally sure why, but I think it is has to do with how the payload is converted to JSON before being passed to the transformer).  When the hash is converted back to JSON (during publishing of the payload to Mitc), the float is converted to a string that is not a valid integer, e.g., "202307181407013106.0"

The length of the ID matters because a float with more than 15 digits is represented using scientific notation.  So, converting a large float to string is what introduces the decimal place in the value sent to Mitc.  HBX ID's in production are fewer than 16 digits, so we are not seeing a bug there (yet).

**Review by mdkaraman — CHANGES_REQUESTED** [review]
Please see my comment in the Conversation tab about limiting the length of the ID's to 15 or fewer digits.

**Review by mdkaraman — DISMISSED** [review]
Test this on my local and looks good!  Unblocked me on submitting FAA applications without requiring any code tweaks or work arounds.

**Review by polographer — DISMISSED** [review]

**Review by mdkaraman — DISMISSED** [review]

**Review by saikumar9 — APPROVED** [review]
lgtm! Good Job @4till2 👏

**Review by mdkaraman — APPROVED** [review]

**Pull request merged**
