### PR TITLE
Simplify resource registry toggler

### PR DESCRIPTION
**Pull request by ZASMan**
MAINT-180558816

### CODE REVIEW

**Review by markgoho — DISMISSED** [review]
please shorten title to be ~50 characters

**Review by markgoho — DISMISSED** [review]
I'm going to request that with this change to the resource registry toggling system that we have multiple developers test this locally prior to merging

**Comment by markgoho** [comment]
@ZASMan please continue to work on this and open for review when it's ready

**Review by bill-transue — APPROVED** [review]
This will simply configuration management by removing the extra set that is kept committed.

**Pull request merged**
