### PR TITLE
Show better validation schema failure errors

### PR DESCRIPTION
**Pull request by bill-transue**
ME-180427968

### CODE REVIEW

**Review by ZASMan — DISMISSED** [review]
Looks good this is going to humanize the errors a bit

**Review by markgoho — DISMISSED** [review]
Where are the spec changes/additions for this?

Could we include a screenshot of the failure error before and after the change?

**Comment by ZASMan** [comment]
> Where are the spec changes/additions for this?
> 
> Could we include a screenshot of the failure error before and after the change?

It's basically impossible to get the data set up locally to create a financial assistance application with the exact conditions set up, including in a cucumber, because our cucumber's around this don't fully pass under Maine settings anyway.

**Review by raghuramg — DISMISSED** [review]
Update  error message to display validation errors. Code changes looks good. Please promote for testing

**Comment by bill-transue** [comment]
I agree with @markgoho, especially when this is updated because that `publish_result` failure is used by a `case` statement in `trunk` and untested. I will update the branch with `trunk` and then write a spec for each `when` in the incoming `case`.

**Comment by bill-transue** [comment]
I was wrong, the `case` statement wasn't in `trunk` yet, I'm going to commit this spec that fits the pull request's additions and then update the other PR with and expand this spec in it to cover the new `when` conditions in it. @markgoho can you please mark as resolved, thanks.

**Review by markgoho — CHANGES_REQUESTED** [review]
remove GHA workflow suite change

**Review by markgoho — APPROVED** [review]

**Pull request merged**
