### PR TITLE
Turn yearly aggregate feature to false

### PR DESCRIPTION
**Pull request by jayreddy519**
[PT-182675622](https://www.pivotaltracker.com/n/projects/2502930/stories/182675622)

### CODE REVIEW

**Review by markgoho — COMMENTED** [review]
@jayreddy519 why are we moving back to a hard coded value?

**Comment by jayreddy519** [comment]
> @jayreddy519 why are we moving back to a hard coded value?

This Branch is for testing purpose only. @markgoho

**Comment by ymhari** [comment]
> > @jayreddy519 why are we moving back to a hard coded value?
> 
> This Branch is for testing purpose only. @markgoho

@jayreddy519 Close the PR if this is only a test branch. You can use the branch for testing and delete it once the testing is done.

**Review by ymhari — CHANGES_REQUESTED** [review]
No need for a PR here.

**Comment by markgoho** [comment]
closing as PR is unnecessary to accomplish the goal

**Pull request closed without merging**
