### PR TITLE
chore: Prevent clicking on the label from triggering the radio button

### PR DESCRIPTION
**Pull request by bbodine1**
# PR Checklist

Please check if your PR fulfills the following requirements
- [ ] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit)
- [ ] Tests for the changes have been added (for bugfixes/features), they use let helpers and before blocks
- [ ] For all UI changes, there is cucumber coverage
- [ ] Any endpoint touched in the PR has an appropriate Pundit policy. For open endpoints, reasoning is documented in PR and code
- [ ] Any endpoint modified in the PR only responds to the expected MIME types.
- [ ] For all scripts or rake tasks, how to run it is documented on both the PR and in the code
- [ ] There are no inline styles added
- [ ] There are no inline javascript added
- [ ] There is no hard coded text added/updated in helpers/views/Javascript. New/updated translation strings do not include markup/styles, unless there is supporting documentation
- [ ] Code does not use .html_safe
- [ ] All images added/updated have alt text
- [ ] Doesn’t bypass rubocop rules in any way

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/187979380

# A brief description of the changes

Current behavior: Tooltip not opening when clicked

New behavior: Tooltip opens when clicked

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

### CODE REVIEW

**Comment by charlienparker** [comment]
Looks good outside of some rebase issues I think?

Also wondering if it's worth storing the label listener in a JS file somewhere, as I know this issue is present on some other pages too.

**Review by charlienparker — COMMENTED** [review]
Looks good assuming all of those stylesheet changes are intended. I think most of it comes from https://github.com/ideacrew/enroll/pull/4047/files? Is this branch meant to be based off of that one?

Also wondering if it's worth refactoring all of the `data-input-label` JS as a function in a JS file somewhere, as I know this issue is present on some other pages too.

**Comment by bbodine1** [comment]
> Looks good assuming all of those stylesheet changes are intended. I think most of it comes from https://github.com/ideacrew/enroll/pull/4047/files? Is this branch meant to be based off of that one?
> 
> Also wondering if it's worth refactoring all of the `data-input-label` JS as a function in a JS file somewhere, as I know this issue is present on some other pages too.

This js was to resolve a very specific issue of our tooltip being added to a label of an input and is an anti-pattern to how default html works. It's probably not a good idea to change it globally.

**Review by charlienparker — APPROVED** [review]

**Comment by charlienparker** [comment]
> > Looks good assuming all of those stylesheet changes are intended. I think most of it comes from https://github.com/ideacrew/enroll/pull/4047/files? Is this branch meant to be based off of that one?
> > Also wondering if it's worth refactoring all of the `data-input-label` JS as a function in a JS file somewhere, as I know this issue is present on some other pages too.
> 
> This js was to resolve a very specific issue of our tooltip being added to a label of an input and is an anti-pattern to how default html works. It's probably not a good idea to change it globally.

All good, I get that it's an antipattern. The same antipattern exists on at least one of the other income pages that I know of, so we're going to need to fix it there too. I have no problem copying the script tag into that page as well, but I was just wondering if we think it's good to dry up the code instead and store this as a function in one of our JS files so that we don't have to repeat this script in the other page(s) where this problem is.

**Review by ATBull81 — APPROVED** [review]

**Pull request merged**
