### PR TITLE
fixes vulnerable link using noopener noreferrer

### PR DESCRIPTION
**Pull request by Battula**
[ME-184110334](https://www.pivotaltracker.com/story/show/184110334)

### CODE REVIEW

**Review by TonyHasIdeas — DISMISSED** [review]
I was not able to do a manual QA based on the comment in the ticket, however these code changes look correct. LGTM!.  I would suggest the second reviewer does a manual QA with a user that has access to the links mentioned in the ticket.

**Review by kristinmerbach — APPROVED** [review]
LGTM!

**Review by j1joey — APPROVED** [review]
LGTM Syntax Wise

**Review by TonyHasIdeas — APPROVED** [review]
LGTM, needs to still be QA'd.  

Also would be nice to QA any areas of the code that the "Proc.new" to "proc" changes occurred on.

**Pull request merged**
