### PR TITLE
include evidences to calculate best_verification_due_date

### PR DESCRIPTION
**Pull request by harshaellanki**
ME-180437693

### CODE REVIEW

**Review by saipraveen18 — APPROVED** [review]
Set due date for FAA verification types.

**Review by markgoho — CHANGES_REQUESTED** [review]
@harshaellanki can we simplify the PR title to be approx 50 characters long?

and are we doing three separate things in this PR?

**Comment by harshaellanki** [comment]
> @harshaellanki can we simplify the PR title to be approx 50 characters long?
> 
> and are we doing three separate things in this PR?

@markgoho Yes all the 3 things related to rrv

**Comment by markgoho** [comment]
Okay can we summarize the change with respect to rrv?

**Review by markgoho — APPROVED** [review]

**Pull request merged**
