### PR TITLE
aa contrast compliance for FAA checklist

### PR DESCRIPTION
**Pull request by ATBull81**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/story/show/186499203

# A brief description of the changes

Current behavior: Page functions normally, needs cucumber

New behavior: Cucumber tests added

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name: CONTRAST_LEVEL_AA_IS_ENABLED

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

Screenshot 2023-12-18 at 8 45 52 AM

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

### CODE REVIEW

**Review by scaustin34 — DISMISSED** [review]
LGTM! 

as a small note unrelated to this specific PR, might I suggest updating the ENV var (`CR97_IS_ENABLED`) to something that is more explanatory? The CR#s are really easy to get confused/not inherently descriptive. Speaking from the position of someone slightly external, i don't know what all that var would entail.

**Comment by ATBull81** [comment]
> LGTM!
> 
> as a small note unrelated to this specific PR, might I suggest updating the ENV var (`CR97_IS_ENABLED`) to something that is more explanatory? The CR#s are really easy to get confused/not inherently descriptive. Speaking from the position of someone slightly external, i don't know what all that var would entail.

Ah good catch, @mdkaraman actually updated the ENV variable last week and I had been using the old one in the PR descriptions still. It is updated in the description to 'CONTRAST_LEVEL_AA_IS_ENABLED'

**Review by scaustin34 — DISMISSED** [review]
LGTM!

**Review by scaustin34 — DISMISSED** [review]

**Review by mdkaraman — DISMISSED** [review]
Looks good!  Includes an update to use the resource registry switch instead of the raw env variable in all cucumbers moving forward.

**Review by scaustin34 — DISMISSED** [review]

**Review by mdkaraman — APPROVED** [review]

**Review by scaustin34 — APPROVED** [review]

**Pull request merged**
