### PR TITLE
csr warning display for mthh applicants with csr

### PR DESCRIPTION
**Pull request by kristinmerbach**
ME-183703783

### CODE REVIEW

**Review by vkghub — CHANGES_REQUESTED** [review]
can you add a cucumber scenario to check the pop up message?

**Comment by markgoho** [comment]
> can you add a cucumber scenario to check the pop up message?

Good catch @vkghub --- I'm wondering as an alternative, is there a way to check that the modal renders in an rspec? Or does this _have to be_ a cucumber?

**Comment by kristinmerbach** [comment]
> > can you add a cucumber scenario to check the pop up message?
> 
> Good catch @vkghub --- I'm wondering as an alternative, is there a way to check that the modal renders in an rspec? Or does this _have to be_ a cucumber?

Adjusted so the logic is in a testable view helper instead

**Review by vkghub — CHANGES_REQUESTED** [review]
As discussed, requested for below changes
- Add a unit test to verify pop up message. I would suggest cucumber.
- refer this file : features/insured/individual_assisted_signup_dialog_box.feature if adding cucumber scenario.
- code is duplicated, which requires code update in multiple places when there is change needed. Initial commit was the right change for this ticket.

**Review by vkghub — APPROVED** [review]

**Pull request merged**
