### PR TITLE
update doc type, logic in identity datatable

### PR DESCRIPTION
**Pull request by nisanthyaganti9**
IVL-181791806

https://github.com/code-and-effect/effective_datatables/tree/2.6.14#testing
This DSL is provided by effective datatables and specs is not implemented, see link above.

### CODE REVIEW

**Review by saikumar9 — CHANGES_REQUESTED** [review]
Some scenarios are missing.

**Review by saikumar9 — APPROVED** [review]
LGTM!

**Comment by markgoho** [comment]
@nisanthyaganti9 please update ticket reference to use format `ME-` or `IVL-`

also, where is the test coverage for this change?

lastly, please shorten title to ~50 characters

**Comment by nisanthyaganti9** [comment]
> @nisanthyaganti9 please update ticket reference to use format `ME-` or `IVL-`
> 
> also, where is the test coverage for this change?
> 
> lastly, please shorten title to ~50 characters

what's the difference b/w adding ticket link vs referencing `IVL-` ? i remember asking this earlier, but never got answered. Adding link seems stright forward & less error prone compared to referencing incorrect tag.

test - https://github.com/code-and-effect/effective_datatables/tree/2.6.14#testing not yet implemented.

PR title - shortened. (It would be great if somehow GH can alert when length > 50, it didn't happened)

@markgoho

**Comment by markgoho** [comment]
> what's the difference b/w adding ticket link vs referencing `IVL-` ? i remember asking this earlier, but never got answered. Adding link seems stright forward & less error prone compared to referencing incorrect tag.
> 
consistency
> test - https://github.com/code-and-effect/effective_datatables/tree/2.6.14#testing not yet implemented.
> 
if we make a change to production code (display logic it looks like here) I'd expect there to be an updated test -- if not, I'm expecting there to be some explanation of why there's no updated/changed test

I don't know what the above link means, can you provide more information on what that gem has to do with our ability to cover this change with our own tests?

> PR title - shortened. (It would be great if somehow GH can alert when length > 50, it didn't happened)

Thanks! We should also be using the present imperative tense on verbs, so `update` instead of `updating` -- I'll get this

**Comment by nisanthyaganti9** [comment]
> > what's the difference b/w adding ticket link vs referencing `IVL-` ? i remember asking this earlier, but never got answered. Adding link seems stright forward & less error prone compared to referencing incorrect tag.
> 
> consistency
> 
> > test - https://github.com/code-and-effect/effective_datatables/tree/2.6.14#testing not yet implemented.
> 
> if we make a change to production code (display logic it looks like here) I'd expect there to be an updated test -- if not, I'm expecting there to be some explanation of why there's no updated/changed test
> 
> I don't know what the above link means, can you provide more information on what that gem has to do with our ability to cover this change with our own tests?
> 
> > PR title - shortened. (It would be great if somehow GH can alert when length > 50, it didn't happened)
> > Thanks! We should also be using the present imperative tense on verbs, so `update` instead of `updating` -- I'll get this

consistency - why not keeping ticket reference & make this a consistent thing. This way, we can avoid someone referencing incorrect label. I saw a few tickets labeled as `ME-` instead `IVL-` viceversa and hard to find ticket. If we keep link, there very less chances this can go wrong.

This DSL is provided by effective data tables gem. that is the dependancy.

**Pull request merged**
