### PR TITLE
fix account transfer erroneously assigning county names

### PR DESCRIPTION
**Pull request by ZASMan**
ME-180361806

### CODE REVIEW

**Comment by ZASMan** [comment]
Ok, so it turns out we might not need this. @saimekala07 said the data can be corrected in enroll later.

**Comment by ZASMan** [comment]
ok actually we might need this

**Review by mdkaraman — APPROVED** [review]

**Review by markgoho — CHANGES_REQUESTED** [review]
Please update PR title to describe issue besides `messed up`, e.g. `malformed`, `corrupted`, etc.

Please add ticket reference in comment box

**Comment by ZASMan** [comment]
> Please update PR title to describe issue besides `messed up`, e.g. `malformed`, `corrupted`, etc.
> 
> Please add ticket reference in comment box

how about "erroneously assigned"

**Review by markgoho — APPROVED** [review]

**Pull request merged**
