### PR TITLE
bootstrap 4 upgrade

### PR DESCRIPTION
**Pull request by kristinmerbach**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes/features)

# PR Type
What kind of change does this PR introduce?

This is the complete refactor of the UI. Details on individual commits are on the PRs that came into this branch.

- [ ] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: This is not one singular ticket but multiple epics: 
* Bootstrap Upgrade: https://www.pivotaltracker.com/epic/show/5231029
* CR-106: https://www.pivotaltracker.com/epic/show/5260763
* CR-107: https://www.pivotaltracker.com/epic/show/5270256

# A brief description of the changes

Current behavior: Old outdated UI based on Bootstrap 3

New behavior: New UI based on Bootstrap 4

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable names:
BS4_CONSUMER_FLOW_IS_ENABLED -> used for all pages in the consumer flow (aka, that can be used by an individual looking for coverage)
BS4_BROKER_FLOW_IS_ENABLED -> used for all broker specific pages
CHOOSE_SHOPPING_METHOD_IS_ENABLED -> adds a new page to the plan shopping flow to send users to Checkbook rather than our plan shopping
SEND_EXTRA_FIELDS_TO_CHECKBOOK_IS_ENABLED -> sends two new fields to the checkbook service in order to enhance the Checkbook UI
CANCELLATION_REASON_FIELD_IS_ENABLED -> Adds a new field to the cancel plan form to be stored in the data warehouse.
MASK_SSN_UI_FIELDS -> hides full SSNs from the UI. For non-inputs, they have been removed from the UI. For inputs they can be made visible (with the proper permissions) by clicking the "eye" icon in the input
SENSOR_TOBACCO_CARRIER_USAGE_IS_ENABLED -> hides the tobacco use question from the UI and sends a default U to the carriers.

- [ ] DC
- [X] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

### CODE REVIEW

**Review by saikumar9 — DISMISSED** [review]
✅🎉👌🔥

**Review by polographer — DISMISSED** [review]

**Comment by polographer** [comment]
a big step in the right (UI) direction

**Review by polographer — APPROVED** [review]
Amazing work from the whole team, this raises the bar of what we can do on UI

**Review by saikumar9 — APPROVED** [review]
👏 🔥

**Pull request merged**
