### PR TITLE
Sets client RR env variables for account transfer

### PR DESCRIPTION
**Pull request by ymhari**
[RM-182454235](https://www.pivotaltracker.com/story/show/182454235)

### CODE REVIEW

**Review by markgoho — COMMENTED** [review]
@ymhari should we be adding this to the ME and "base" config as well?

**Comment by ymhari** [comment]
> @ymhari should we be adding this to the ME and "base" config as well?

@markgoho We are testing only DC. ME already has this feature turned on in PROD.

**Review by markgoho — DISMISSED** [review]
can we add `_IS_ENABLED` to these environment variables to set the pattern for feature flags as having that suffix?

**Comment by ymhari** [comment]
> can we add `_IS_ENABLED` to these environment variables to set the pattern for feature flags as having that suffix?

Makes sense will do it now.

**Comment by markgoho** [comment]
@ymhari not a blocker to merging, but I think the next logical question here is, "What is the purpose of having this duplicate code?" and "How could we DRY this up?"

Ultimately, I wonder if there could be a source for config that is entirely environment-driven and so would only need a single file to control config. Where we hard-code config (site name, phone number, etc.) that must continue to exist on a per-client basis.

**Review by markgoho — APPROVED** [review]
This change will move the source of these values to the environment in which the application is running.

**Pull request merged**
