### PR TITLE
enables the slcsp calculator API to return valid values on happy path; 1 person 1 house

### PR DESCRIPTION
**Pull request by polographer**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [x] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

# What is the ticket # detailing the issue?

Ticket: 
IVL-184138450

# A brief description of the changes

Current behavior:
the slcsp calculator API returns random values for the months

New behavior:
the slcsp calculator API can calculate happy path 1 person, 1 house

# Environment Variable

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. Please share the name of the variable below that would enable/disable the feature and which client it applies to.

Variable name:

- [ ] DC
- [ ] ME

### CODE REVIEW

**Comment by markgoho** [comment]
@polographer I sent the following payload locally but got `{"error":"Invalid parameters"}`

``` json
{
    "householdConfirmation": true,
    "householdCount": 2,
    "taxYear": "2022",
    "state": "ME",
    "members": [
        {
            "primaryMember": true,
            "relationship": "self",
            "name": "Mark",
            "dob": {
                "month": 1,
                "day": 1,
                "year": 1970
            },
            "residences": [
                {
                    "county": {
                        "zipcode": "04003",
                        "name": "Cumberland County",
                        "fips": "23005",
                        "state": "ME"
                    },
                    "months": {
                        "jan": true,
                        "feb": true,
                        "mar": true,
                        "apr": true,
                        "may": true,
                        "jun": true,
                        "jul": true,
                        "aug": true,
                        "sep": true,
                        "oct": true,
                        "nov": true,
                        "dec": true
                    }
                }
            ],
            "coverage": {
                "jan": true,
                "feb": true,
                "mar": true,
                "apr": true,
                "may": true,
                "jun": true,
                "jul": true,
                "aug": true,
                "sep": true,
                "oct": true,
                "nov": true,
                "dec": true
            }
        },
        {
            "primaryMember": false,
            "relationship": "spouse",
            "name": "Nella",
            "dob": {
                "month": 1,
                "day": 2,
                "year": 1980
            },
            "residences": [
                {
                    "county": {
                        "zipcode": "",
                        "name": "",
                        "fips": "",
                        "state": ""
                    },
                    "months": {
                        "jan": false,
                        "feb": false,
                        "mar": false,
                        "apr": false,
                        "may": false,
                        "jun": false,
                        "jul": false,
                        "aug": false,
                        "sep": false,
                        "oct": false,
                        "nov": false,
                        "dec": false
                    }
                }
            ],
            "coverage": {
                "jan": true,
                "feb": true,
                "mar": true,
                "apr": true,
                "may": true,
                "jun": true,
                "jul": true,
                "aug": true,
                "sep": true,
                "oct": true,
                "nov": true,
                "dec": true
            }
        }
    ]
}
```

**Comment by polographer** [comment]
@markgoho on the example payload, you are sending 2 persons, right now only allows 1 person

**Comment by markgoho** [comment]
Update, here is the command I used to test
``` console
curl -X POST \
http://localhost:3000/api/v2/slcsp_calculator/estimate \
-H 'Content-Type: application/json' \
-d '{"householdConfirmation":true,"householdCount":1,"taxYear":"2022","state":"ME","members":[{"primaryMember":true,"relationship":"self","name":"Mark","dob":{"month":1,"day":1,"year":1970},"residences":[{"county":{"zipcode":"04003","name":"Cumberland County","fips":"23005","state":"ME"},"months":{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}}],"coverage":{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}}]}'
```
and here is the response I got
```
{"jan":0,"feb":0,"mar":0,"apr":0,"may":0,"jun":0,"jul":0,"aug":0,"sep":0,"oct":0,"nov":0,"dec":0}
```

**Review by markgoho — APPROVED** [review]
I'm approving as far as the anticipated payload returning a reasonable response.

Would appreciate anyone wanting to give rails-specific feedback to do so

**Review by saikumar9 — APPROVED** [review]
LGTM!

**Review by mdkaraman — APPROVED** [review]
This looks as far as an initial implementation for the "happy path."  I spoke with @polographer about some possible ways to make this more robust/secure, e.g., rescuing the JSON parse method if it fails, and he already has plans to include those improvements in the next iteration.

**Comment by polographer** [comment]
@mdkaraman will do the json rescue, definitely needed

**Pull request merged**
