### PR TITLE
plan shopping side nav for back to account

### PR DESCRIPTION
**Pull request by yosefserkez**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes / features)

# PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update version)

# What is the ticket # detailing the issue?

Ticket: TT6-184980444

# A brief description of the changes

Current behavior:

New behavior:

# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable that is used to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name: BACK_TO_ACCOUNT_ALL_SHOP_IS_ENABLED

- [ ] DC
- [x] ME

# Additional Context
Include any additional context that may be relevant to the peer review process.

There are multiple scenarios where the user can be shopping for plans. See the comment below for a summary of the scenarios handled in code. This PR aims to support pre-existing design by implementing an abstraction that supports the new design. Much of this functionality should live in a helper function but to do it properly will require a larger refactor.

### CODE REVIEW

**Comment by yosefserkez** [comment]
Here are the different scenarios:

1. Scenario 1:
   - `@change_plan` is blank.
   - `@market_kind` is "individual".
   - `@enrollment_kind` is blank.
   - `is_under_open_enrollment?` is true.
   In this scenario, the code will render the partial `'shared/individual_progress'` with the local variable `step` set to '3'.

2. Scenario 2:
   - `@change_plan` is blank.
   - `@market_kind` is "individual".
   - `@enrollment_kind` is not blank or `is_under_open_enrollment?` is false.
   In this scenario, the code will render the partial `'shared/sep_progress'` with the local variables `step` set to '4', `continue_disabled` set to `false`, and `button_continue` set to `true`.

3. Scenario 3:
   - `@change_plan` is blank.
   - `can_shop_resident?(@person)` is true.
   In this scenario, the code will render the partial `'shared/coverall_progress'` with the local variable `step` set to '4'.

4. Scenario 4:
   - `@change_plan` is blank.
   - Neither of the previous conditions are met.
   In this scenario, the code will render the partial `'shared/signup_progress'` with the local variable `step` set to '4'.

5. Scenario 5:
   - `@change_plan` is "change_by_qle".
   In this scenario, the code will render the partial `'shared/qle_progress'` with the local variables `step` set to '2' and `show_button` set to `false`.

6. Scenario 6:
   - `@change_plan` is "change_plan".
   - Either `@market_kind` is "individual" and `is_under_open_enrollment?` is false.
   - Or `@enrollment_kind` is 'sep'.
   In this scenario, the code will render the partial `'shared/sep_shop_for_plans_progress'` with the local variable `step` set to '2'.

7. Scenario 7:
   - `@change_plan` is "change_plan".
   - Either `@market_kind` is not "individual" or `is_under_open_enrollment?` is true.
   In this scenario, the code will render the partial `'shared/shop_for_plans_progress'` with the local variable `step` set to '1' and `show_waive` set to `true`.

note: `@change_plan` indicates the presence of `change_plan=` as a url parameter.

**Review by erubinst — DISMISSED** [review]
Looks good to me

**Review by mdkaraman — DISMISSED** [review]
Thank you for the excellent walk through and outline of all the scenarios.  This not only introduces the new feature requested but streamlines the existing implementation so that it's easier to follow moving forward.  Also replaces some hardcoded strings with translations and cleans up spec/cucumbers.  Awesome job!

**Comment by yosefserkez** [comment]
Turns out there are other usages of these partials which may impact the scope of testing required to ensure existing behavior is not impacted by these changes. The latest commits pass more control into the hands of the original partials to try and reconcile for this. Additionally I found at least one instance of another files usage of these partials that broke the styling. I added a div container to resolve that.

ps. the regex to get all usages `shared/(individual|sep|signup|qle|sep_shop_for_plans|shop_for_plans)_progress`

**Review by mdkaraman — APPROVED** [review]

**Review by erubinst — APPROVED** [review]

**Pull request merged**
