### PR TITLE
Broker Staff Pundit Policy - Person Update

### PR DESCRIPTION
**Pull request by jayreddy519**
# PR Checklist

Please check if your PR fulfills the following requirements
- [x] The title follows our [guidelines](https://github.com/ideacrew/enroll/blob/trunk/CONTRIBUTING.md#commit
)
- [ ] Tests for the changes have been added (for bugfixes/features)

# PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (requires Feature flag)
- [ ] Data fix or migration (inert code, no impact until run)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Dependency updates (e.g., add a new gem or update to a version)

# What is the ticket # detailing the issue?

Ticket: https://www.pivotaltracker.com/n/projects/2640059/stories/187226903

# A brief description of the changes

Current behavior: Broker agency staff role users are unable to update person under manage family

When a person has Broker staff role, 
Clicks on families associated to the agency
Tries to save primary person under manage family
Access Not Allowed error on saving the person record

New behavior: Broker agency staff role users should be unable to update person under manage family

When a person has Broker staff role, 
Clicks on families associated to the agency
Tries to save primary person under manage family
Person should be saved without any issues.

error
# Feature Flag

For all new feature development, a feature flag is required to control the exposure of the feature to our end users. A feature flag needs a corresponding environment variable to initialize the state of the flag. Please share the name of the environment variable below that would enable/disable the feature and which client(s) it applies to.

Variable name:

- [ ] DC
- [ ] ME

# Additional Context
Code flow ->
app/controllers/people_controller.rb:10 in update action
app/policies/person_policy.rb

# AppScan CodeSweep Failure
In the event of a failed check on the AppScan CodeSweep step of our GitHub Actions workflow, please review the False Positive protocol outlined here: appscan_codesweep/CODESWEEP_FALSE_POSITIVES_README.MD

Add all required notes to this section if the failure is a suspected false positive.

### CODE REVIEW

**Review by jacobkagon — APPROVED** [review]
Allows broker staff the ability to edit family and employer data. This looks good!

**Comment by jayreddy519** [comment]
features/plan_shopping/employee_plan_filters.feature this cucumber is failing , this might be a flickering one, I will rerun the failed one after this run.

**Review by saikumar9 — CHANGES_REQUESTED** [review]
@jayreddy519 Everything is looking good. Please add tests using `broker_agency_staff_roles`.

**Review by saikumar9 — APPROVED** [review]
lgtm!

**Review by saikumar9 — APPROVED** [review]

**Review by vkghub — APPROVED** [review]
LGTM

**Review by jacobkagon — APPROVED** [review]

**Review by vkghub — APPROVED** [review]

**Pull request merged**
