### PR TITLE
revert back code because of preceding enrollment tile end date issue

### PR DESCRIPTION
**Pull request by saipraveen18**
ME-183948910

### CODE REVIEW

**Review by nks2109 — APPROVED** [review]
it updates the end date of the previously terminated enrollment

**Review by markgoho — CHANGES_REQUESTED** [review]
let's reserve `revert` in a PR title for revert commits

is this actually reverting a specific commit?

**Comment by markgoho** [comment]
Shouldn't we revert this commit? https://github.com/ideacrew/enroll/pull/2153

**Comment by markgoho** [comment]
closed in favor of https://github.com/ideacrew/enroll/pull/2426

**Pull request closed without merging**
