### PR TITLE
log user data when appending enrollment fails

### PR DESCRIPTION
**Pull request by eidarus**
MAINT-181060600

### CODE REVIEW

**Comment by markgoho** [comment]
@eidarus is this the kind of change that we could cover with a test?

**Review by bill-transue — CHANGES_REQUESTED** [review]
We've got a couple of problems with this rescue, first`bc_period` is going to be nil so you won't be able to `bc_period.start_on` in the log message. But even bigger than that is this would allow the enrollment notice to continue even though the notice's `ivl_open_enrollment_start_on` and `open_enrollment_end_on` won't be set. Instead of rescuing in this sub-info-setting-method let's move the rescue and logger to `app/jobs/ivl_notices_notifier_job.rb` itself and make rescue in line with the method definition like:
```
def perform(person_id, event, options = {})
  Resque.logger.level = Logger::DEBUG
  ...
rescue StandardError => e
  Rails.logger.error { "Could not generate IVL open enrollment notice event #{event} due to #{e} for Person: #{person_id}\n#{e.backtrace.join("\n")}" }
end
```

Also @markgoho is right, write a spec that ensures this doesn't generate an exception when bc_period can't be determined and that a message is logged. You can `expect` that `Rails.logger.error` was called with stubs.

**Review by bill-transue — APPROVED** [review]
Specs and adds logger for IvlNotice job that encounter exceptions.

**Review by bill-transue — CHANGES_REQUESTED** [review]
Can you `raise e` inside the `rescue` so the exception isn't shallowed?

**Review by bill-transue — APPROVED** [review]
Good work, will help you track down people this job is erroring on. You'll need to check Graylog for this output. Good luck @eidarus!

**Pull request merged**
