### PR TITLE
parallel processing of bulk OV-RRV & verification reminder requests

### PR DESCRIPTION
**Pull request by vrbattula**
[ME-181269028](https://www.pivotaltracker.com/story/show/181269028)

### CODE REVIEW

**Review by raghuramg — APPROVED** [review]
Reviewed the event source publisher/susbcribers added to process batch reminder notices and rrv requests.

Code looking good. Dev fired the events locally and they're getting picked up by the subscribers.

 Please promote this for testing

**Comment by jacobkagon** [comment]
@vrbattula does this need a QA plan?

**Comment by harshaellanki** [comment]
This PR can be deleted

**Comment by davidplappert** [comment]
this PR can be deleted. 

[2:41 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130494870789)
[Varun Battula](https://app.slack.com/team/U0122BME6BD) Hi David

[2:41 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130507269599)
[David Plappert](https://app.slack.com/team/U0LJCCWF8) hey hey

[2:42 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130520913529)
[Varun Battula](https://app.slack.com/team/U0122BME6BD) How are you ? Its been long time

[2:42 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130532299609)
[David Plappert](https://app.slack.com/team/U0LJCCWF8) very busy, but good. How are you?

[2:42 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130542375339)
[Varun Battula](https://app.slack.com/team/U0122BME6BD) Good, thanks

[2:43 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130617268379)
Wanted a quick favor from you.
Can you please add a comment on this PR saying that its okay to delete ?
I have created this PR with my personal GH account and will need admin permission to delete it.
https://github.com/ideacrew/enroll/pull/1658
Please add a comment something like - This PR can be deleted

[2:44 PM](https://ideacrew.slack.com/archives/D0336NN51JT/p1645130645508229)
Its already addressed via 1659

**Pull request closed without merging**
